// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClf5eeivkrqpiElfQORrxhcqoki5XYqJI',
    appId: '1:257746472366:web:8bf0caf55639c0508a4c3f',
    messagingSenderId: '257746472366',
    projectId: 'footballclick-cb698',
    authDomain: 'footballclick-cb698.firebaseapp.com',
    storageBucket: 'footballclick-cb698.appspot.com',
    measurementId: 'G-18H0W7PRE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6xObnkTA_VJaKY62wPeRgGpXovqrip-c',
    appId: '1:257746472366:android:0f6a760880bf2c148a4c3f',
    messagingSenderId: '257746472366',
    projectId: 'footballclick-cb698',
    storageBucket: 'footballclick-cb698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqGwrITsGkDyNLsQIyAIEDExtdMALQ_Y4',
    appId: '1:257746472366:ios:cf7db3befead6e5b8a4c3f',
    messagingSenderId: '257746472366',
    projectId: 'footballclick-cb698',
    storageBucket: 'footballclick-cb698.appspot.com',
    iosBundleId: 'com.kimdane.footballclick',
  );
}
